### ISSUE TITLE
Zpětná vazba

### ISSUE THREAD

**Issue by IxAriela** [saurinne/Koderka_u1_zivotopis#1]
Ahoj, líbí se mi, jakou sis s tím dala práci, i s obsahem, včetně uvedení autorů fotek (i když, od studentky KISKu to není překvapivé) :)

K HTML nemám žádnou připomínku, naopak jsou super vyplněné alty u obrázků (jasně, měla by to být samozřejmost, ale není kolikrát i u profesionálů) a použití mailto :+1: 

U CSS spíš praktické věci, k opravě ti dám spíš drobnosti.

Chválím použití procent na horizontální linii, dobrá příprava na responsiv :) u základní šířky webu se většinou používá nějaký obal (nejčastější pojmenování je asi container), který má nastaven šířku (např. max-width: 1440px;) a margin: 0 auto;, které to zarovná doprostřed. Čistě na body se většinou tyto mezery nedávají.

U obrázků se většinou určuje spíše šířka než výška, právě kvůli responsivu. Ale chápu, že tady se více hodila ta výška :)

Pro přehlednost kódu se i v css většinou řadí třídy a tagy tak, jak jsou použity na stránce. Tj. bych hledala header nahoře, footer dole. U malých projektů je to dost jedno, ale jak to pak narůstá, tak už je to znát.

Prosím oprav v css:

- [x] u H1 máš 2 středníky
- [x] v zápatí máš overflow: cover;, jsem si dost jistá, že cover u overflow neexistuje.

**Comment by saurinne** [comment]
Díky, hotovo
